# Generated by Django 4.2.2 on 2024-01-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForBlog',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=20)),
                ('dateAttr', models.CharField(max_length=30)),
                ('day', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('commCount', models.IntegerField()),
                ('publisher', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=10)),
                ('subtitle', models.TextField()),
                ('single', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalClients',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=50)),
                ('hover', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalHeader',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalTeam',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.TextField(max_length=100)),
                ('content', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalTestimonial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=30)),
                ('body', models.TextField()),
            ],
        ),
    ]
