# Generated by Django 4.2.2 on 2023-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('eMail', models.EmailField(max_length=50)),
                ('healthComplaints', models.CharField(max_length=50)),
            ],
        ),
    ]
