# Generated by Django 4.2.2 on 2023-12-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqQuestions',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('toggle', models.CharField(blank=True, max_length=20)),
                ('body', models.TextField()),
            ],
        ),
    ]
