# Generated by Django 4.2.2 on 2023-12-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsCard',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('icon', models.TextField(max_length=70)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('icon', models.TextField(max_length=70)),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
