# Generated by Django 4.2.2 on 2023-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IconBox',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=70, unique=True)),
                ('title', models.CharField(max_length=70, unique=True)),
                ('subtitle', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBox',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('subtitle', models.TextField(max_length=250)),
            ],
        ),
    ]
